//==============================================================================
// File        : MohidNGHDF5Writer2D.hpp
// Author      : Joao Flavio Vieira de Vasconcellos
// Version     : 1.0
// Description : MohidNG 2D Voronoi mesh package writer.
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.
//
// @file MohidNGHDF5Writer2D.hpp
// @brief Writes audited 2D FV meshes using the MohidNG HDF5 package schema.
// @ingroup vmm_export
//==============================================================================
#pragma once

//==============================================================================
// c++ includes
//==============================================================================
#include <filesystem>
#include <string>


//==============================================================================
// VoronoiMeshMaker includes
//==============================================================================
#include <vmm/mesh/FiniteVolumeMesh2D.hpp>
#include <vmm/raster/RasterField2D.hpp>

namespace vmm::io {

inline constexpr const char* kMohidNGVoronoiMeshPackageSchemaVersion = "mohidng.voronoi_mesh_package/0.1";

struct MohidNGHDF5Writer2DOptions final {
    std::string coordinate_reference_system{"local Cartesian"};
    std::string note{"Generated by VoronoiMeshMaker."};
    std::string raster_field_name{"raster"};
    const vmm::raster::CellRasterSamples2D* raster_samples{nullptr};
    bool require_valid_mesh{true};
};

void write_mohidng_hdf5_mesh_2d(const std::filesystem::path& file_path,
                                const vmm::mesh::FiniteVolumeMesh2D& mesh,
                                const MohidNGHDF5Writer2DOptions& options = {});

} // namespace vmm::io
