#pragma once
//==============================================================================
// Name        : BisectorHalfplane.hpp
// Project     : VoronoiMeshMaker (VMM)
// Module      : Voronoi2D / Clipping
// Description : Bisector halfplane construction for Voronoi cells.
// License     : GNU GPL v3
//==============================================================================

/**
 * @file BisectorHalfplane.hpp
 * @brief Builds the halfplane that keeps points closer to one site than another.
 */

#include <VoronoiMeshMaker/ErrorHandling/CoreErrors.h>
#include <VoronoiMeshMaker/ErrorHandling/Macros.h>
#include <VoronoiMeshMaker/Sites2D/Site2D.hpp>
#include <VoronoiMeshMaker/Voronoi2D/Clipping/Halfplane2D.hpp>

VORMAKER_NAMESPACE_OPEN
VORONOI2D_NAMESPACE_OPEN

/**
 * @brief Construct the perpendicular-bisector halfplane for a site pair.
 *
 * For a cell generated by `owner`, the returned halfplane keeps the side of the
 * bisector closer to `owner` than to `neighbor`:
 *
 * `2*(neighbor-owner).x*x + 2*(neighbor-owner).y*y <= |neighbor|^2 - |owner|^2`
 */
struct BisectorHalfplane {
    using Point2 = ::vmm::s2d::Point2;
    using Real = ::vmm::s2d::Real;

    [[nodiscard]] static Halfplane2D between(Point2 owner, Point2 neighbor) {
        const Real dx = neighbor.x - owner.x;
        const Real dy = neighbor.y - owner.y;
        const Real norm2 = dx * dx + dy * dy;
        if (norm2 <= ::vmm::constants::kEpsilon * ::vmm::constants::kEpsilon) {
            VMM_THROW(::vmm::error::CoreErr::InvalidArgument,
                      {{"where", "BisectorHalfplane"},
                       {"reason", "coincident_sites"}});
        }

        return Halfplane2D{
            Real{2} * dx,
            Real{2} * dy,
            // Factor the difference of squares before rounding to Real.
            static_cast<Real>(static_cast<long double>(dx)
                    * (static_cast<long double>(neighbor.x) + owner.x)
                + static_cast<long double>(dy)
                    * (static_cast<long double>(neighbor.y) + owner.y))
        };
    }
};

VORONOI2D_NAMESPACE_CLOSE
VORMAKER_NAMESPACE_CLOSE
